#!/bin/bash

declare dir="";
if [[ "${PWD}" == "server" ]]; then
    dir="src";
else if [[ "${PWD}" == "storyboard" ]]; then
    dir="server/src";
else if [[ "${PWD}" == "src" ]]; then
    dir="";
else
    echo "Change directory to either 'storyboard' or 'storyboard/server'"
    exit 1;
fi;

[ "${dir}" ] &&
    pushd "${dir}" >/dev/null;

(
    (
        echo "Building Windows binary..";
        GOOS=windows go build
    ) &&

    (
        echo "Building Mac binary...";
        GOOS=darwin go build &&
            mv -f server server_darwin
    ) &&

    (
        echo "Building Linux binary...";
        GOOS=linux go build &&
            mv -f server server_linux
    )
) &&
    echo "Success!"