#!/bin/bash

declare os="$(uname -a | awk '{print $1;}')";

#files=($(ls --hide='*_test.go' | grep .go)); gomon "${files[@]}"
if [[ os == "Linux" ]]; then
    files=($(ls --hide='*_test.go' | grep .go));
else 
    files=(handler.go main.go schema.go)
done;

go run "${files[@]}"